/** type value */
export type Typeof =
  | 'number'
  | 'function'
  | 'string'
  | 'boolean'
  | 'object'
  | 'undefined'
  | 'null'
  | 'array'
  | 'date'
  | 'set'
  | 'map'
  | 'symbol'
  | 'bigint'
  | 'bigint64array'
  | 'biguint64array'
  | 'regexp'
  | 'int8array'
  | 'uint8array'
  | 'int16array'
  | 'uint16array'
  | 'float32array'
  | 'float64array'
  | 'int32array'
  | 'uint32array'
  | 'weakmap'
  | 'weakset'
  | 'generatorfunction'
  | 'generator'
  | 'error'
  | 'evalerror'
  | 'rangeerror'
  | 'referenceerror'
  | 'syntaxerror'
  | 'typeerror'
  | 'urierror'
  | 'aggregateerror'
  // 该错误非标准，且 ts 不存在
  // | 'internalerror'
  | 'uint8clampedarray'
  | 'sharedarraybuffer'
  | 'promise'
  | 'asyncfunction'
  | 'dataview'
  | 'arraybuffer'
  | 'audiobuffer'
  | 'intl.collator'
  | 'intl.datetimeformat'
  | 'intl.displaynames'
  /// 该规则较新，暂不适用
  // | 'intl.durationformat'
  | 'intl.listformat'
  | 'intl.locale'
  | 'intl.numberformat'
  | 'intl.pluralrules'
  | 'intl.relativetimeformat'
  | 'intl.segmenter';
